---
title: "RF"
author: "Bartosz Dąbrowski"
date: "3 05 2020"
output: html_document
---

```{r }
require(tidyverse)
require(stringr)
require(tm)
require(randomForest)
require(ranger)
require(corrplot)
require(rcompanion)
require(caret)
require(mlbench)
```

Do zaimportowania użyłem pakietu readr, aby uniknąć problemu z niepoprawnym odczytywaniem polskich znaków przez read.csv().

```{r }
data <- read_delim("E:/survey_model/dane.tsv", "\t", 
    escape_double = FALSE, trim_ws = TRUE)
head(data,10)
str(data)
```

###Oczyszczanie danych###
###PAMIĘTAJ ŻEBY ŚCIĄGNĄĆ NOWE DANE BO MASZ NOWE ODPOWIEDZI###

```{r }
data<-as.data.frame(data)

#data[,2]<-parse_factor(data[,2],levels=unique(sort(data[,2])))
data[,4]<-parse_factor(data[,4],levels=unique(sort(data[,4])))
data[,5]<-parse_factor(data[,5],levels=c("poniżej 5 tysięcy","5 - 20 tysięcy","20 - 100 tysięcy", "100 - 200 tysięcy","200 - 500 tysięcy","powyżej 500 tysięcy"))
#data[,7]<-parse_factor(data[,7],levels=c("Tak","Nie"))
data[,8]<-parse_factor(data[,8],levels=c("I","II","III","IV","V","Ukończyłem/ukończyłam studia"))
#data[,9]<-parse_factor(data[,9],levels=c("Publiczna","Prywatna"))
#data[,10]<-parse_factor(data[,10],levels=unique(sort(data[,10])))
data[,11]<-parse_factor(data[,11],levels=c("Artystyczna","Ekonomiczna","Pedagogiczna","Techniczna","Uniwersytet","Inna"))
data[,12]<-parse_factor(data[,12],levels=c("Architektura","Automatyka/elektrotechnika","Biologia","Chemia","Dziennikarstwo/komunikacja społeczna","Ekonometria","Ekonomia/finanse","Farmacja","Filologia","Fizyka/astronomia","Geografia","Historia","Informatyka/telekomunikacja","Inżynieria biomedyczna","Inżynieria chemiczna","Inżynieria lądowa/budownictwo/transport","Inżynieria materiałowa","Inżynieria mechaniczna","Inżynieria środowiska/energetyka/górnictwo","Kulturoznawstwo/religioznawstwo","Matematyka","Medycyna","Nauki o bezpieczeństwie","Pedagogika","Prawo/administracja","Psychologia","Socjologia","Sztuki piękne","Technologia żywności","Weterynaria/zootechnika","Zarządzanie","Inne"))
#data[,13]<-parse_factor(data[,13],levels=c("Tak","Nie"))
#data[,14]<-parse_factor(data[,14],levels=c("Tak","Nie"))
#data[,15]<-parse_factor(data[,15],levels=c("Tak","Nie"))
data[,16]<-parse_factor(data[,16],levels=unique(sort(data[,16])))
#data[,17]<-parse_factor(data[,17],levels=c("Tak","Nie"))
#data[,18]<-parse_factor(data[,18],levels=c("Akademik","Dom/mieszkanie rodzinne","Wynajęte mieszkanie","Wynajęty pokój","Inne"))
data[,28]<-parse_factor(data[,28],levels=c("Jeszcze nie pracuję","Przed początkiem studiów","I rok","II rok", "III rok","IV rok","V rok", "Później"))

str(data)
```

```{r}
unique(data[,3])
table(data[,6])
data[,3] <- replace(data[,3],data[,3]=="19, rocznikowo 20", "19")
unique(data[,6])
unique(data[,3])
data[,3]<-as.numeric(data[,3])
Krk<-c('Kraków','Krakow','krk','Krakó','Kraków xD')
data[,6]<-gsub(paste(Krk, collapse = '|'), 'Kraków', data[,6])
Wwa<-c('Warszawa','Wawa','Warszasa')
data[,6]<-gsub(paste(Wwa, collapse = '|'), 'Warszawa', data[,6])
Poznan<-c("Poznań","poznań","Poznan")
data[,6]<-gsub(paste(Poznan, collapse = '|'), 'Poznań', data[,6])
Gd<-c('Gdańsk','Gdansk')
data[,6]<-gsub(paste(Gd, collapse = '|'), 'Gdańsk', data[,6])

Gd<-c("BIAŁYSTOK", "Białystok")
data[,6]<-gsub(paste(Gd, collapse = '|'), 'Białystok', data[,6])

Gd<-c("słupsk", "Słupsk")
data[,6]<-gsub(paste(Gd, collapse = '|'), 'Słupsk', data[,6])

Gd<-c("Deblin", "Dęblin")
data[,6]<-gsub(paste(Gd, collapse = '|'), 'Dęblin', data[,6])

Gd<-c("Toruń, Poznań", "Toruń")
data[,6]<-gsub(paste(Gd, collapse = '|'), 'Toruń', data[,6])

#data[,6] <- replace(data[,6],data[,6]=="BIAŁYSTOK", "Białystok")
#data[,6] <- replace(data[,6],data[,6]=="Gdansk", "Gdańsk")
data[,6] <- replace(data[,6],data[,6]=="Uniwersytet Śląski", "Katowice")
#data[,6] <- replace(data[,6],data[,6]=="słupsk", "Słupsk")
#data[,6] <- replace(data[,6],data[,6]=="Deblin", "Dęblin")
#data[,6] <- replace(data[,6],data[,6]=="Toruń, Poznań", "Toruń")
#data[,6] <- replace(data[,6],data[,6]=="Toruń", "Toruń")
table(data[,6])
str(data)
```

```{r}
data[,2]<-if_else(data[,2]=="Kobieta",1,0)
data[,6]<-parse_factor(data[,6],levels=unique(sort(data[,6])))
data[,9]<-if_else(data[,9]=="Prywatna",1,0)
data[,10]<-if_else(data[,10]=="Zaocznie",1,0)
data[,7]<-if_else(data[,7]=="Tak",1,0)
data[,13:15]<-if_else(data[,13:15]=="Tak",1,0)
data[,17]<-if_else(data[,17]=="Tak",1,0)
```

```{r}
#help(str_detect)
#str_detect(data[,18],coll("Akademik"))
data<-data%>%
  mutate(Akademik=if_else(str_detect(data[,18],coll("Akademik")),1,0),
         Dom_mieszkanie_rodzinne=if_else(str_detect(data[,18],coll("Dom/mieszkanie rodzinne")),1,0),
         Wynajete_mieszkanie=if_else(str_detect(data[,18],coll("Wynajęte mieszkanie")),1,0),
         Wynajety_pokoj=if_else(str_detect(data[,18],coll("Wynajęty pokój")),1,0),
         Inne=if_else(str_detect(data[,18],coll("Inne")),1,0))
```
df - oczyszczona wersja danych
```{r}
df<-data[,-29]
df<-df[,-18]
df<-df[,-1]
```

```{r}
colnames(df)[1:31]<-c('Kobieta','Wiek','Wojewodztwo_pochodzenia', 'Wielkosc_miasta', 'Miasto', 'Wiecej_kierunkow', 'Rok','Prywatna','Zaocznie', 'Typ','Dziedzina','Kola','Organizacje','Samorzad','Srednia','Stypendium','Wiodace','Zapychacze','Zapychacze_dobor','Jezyk','Organizacja_uczelni','Plany','Trudnosc','Przydatnosc','Ogolna_ocena','Praca','Akademik','Dom_mieszkanie_rodzinne','Wynajete_mieszkanie','Wynajety_pokoj','Inne')
str(df)
colnames(df)
```


```{r}



# Calculate a pairwise association between all variables in a data-frame. In particular nominal vs nominal with Chi-square, numeric vs numeric with Pearson correlation, and nominal vs numeric with ANOVA.
# Adopted from https://stackoverflow.com/a/52557631/590437
mixed_assoc = function(df, cor_method="spearman", adjust_cramersv_bias=TRUE){
    df_comb = expand.grid(names(df), names(df),  stringsAsFactors = F) %>% set_names("X1", "X2")

    is_nominal = function(x) class(x) %in% c("factor", "character")
    # https://community.rstudio.com/t/why-is-purr-is-numeric-deprecated/3559
    # https://github.com/r-lib/rlang/issues/781
    is_numeric <- function(x) { is.integer(x) || is_double(x)}

    f = function(xName,yName) {
        x =  pull(df, xName)
        y =  pull(df, yName)

        result = if(is_nominal(x) && is_nominal(y)){
            # use bias corrected cramersV as described in https://rdrr.io/cran/rcompanion/man/cramerV.html
            cv = cramerV(as.character(x), as.character(y), bias.correct = adjust_cramersv_bias)
            data.frame(xName, yName, assoc=cv, type="cramersV")

        }else if(is_numeric(x) && is_numeric(y)){
            correlation = cor(x, y, method=cor_method, use="complete.obs")
            data.frame(xName, yName, assoc=correlation, type="correlation")

        }else if(is_numeric(x) && is_nominal(y)){
            # from https://stats.stackexchange.com/questions/119835/correlation-between-a-nominal-iv-and-a-continuous-dv-variable/124618#124618
            r_squared = summary(lm(x ~ y))$r.squared
            data.frame(xName, yName, assoc=sqrt(r_squared), type="anova")

        }else if(is_nominal(x) && is_numeric(y)){
            r_squared = summary(lm(y ~x))$r.squared
            data.frame(xName, yName, assoc=sqrt(r_squared), type="anova")

        }else {
            warning(paste("unmatched column type combination: ", class(x), class(y)))
        }

        # finally add complete obs number and ratio to table
        result %>% mutate(complete_obs_pairs=sum(!is.na(x) & !is.na(y)), complete_obs_ratio=complete_obs_pairs/length(x)) %>% rename(x=xName, y=yName)
    }

    # apply function to each variable combination
    map2_df(df_comb$X1, df_comb$X2, f)
}
```

```{r}
mixed_assoc(df)#->correlations
#this is definitely not perfect way to check associations, I can understand that field of study is not strong correlated with job, but some correlation has to be
```





```{r}
corrplot(cor(df))
typeof(df)
df<-as.data.frame(df)
typeof(df)
cor(df[1],df[3])
dimnames(df)
#?cor

```




próba random forest


```{r}
#set.seed(42)
#help(ranger)
#outcome<-df[,26]

model<-ranger(formula=Praca~.,data=df,num.trees = 300,respect.unordered.factors = 'order',seed=42)
model

model2 <- train(
  Praca~.,
  tuneLength = 10,
  data = df, 
  method = 'ranger',
  trControl = trainControl(
    method = "cv", 
    number = 5, 
    verboseIter = TRUE
  )
)
model2
plot(model2)
#model<-ranger(formula=outcome~.,data=df,num.trees = 300,respect.unordered.factors = 'order',seed=42)
#model<-randomForest(outcome~.,data=df)


```



